# Generated by Django 2.0.2 on 2018-03-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0002_auto_20180312_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlTemperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_temp', models.IntegerField(default=0)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.Payload')),
            ],
        ),
    ]
