# Generated by Django 2.0.2 on 2018-03-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0003_pltemperatura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlTemperatura',
            new_name='PlTemperature',
        ),
    ]
