# Generated by Django 2.0.2 on 2018-04-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0004_auto_20180320_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type_id', models.IntegerField(default=0)),
                ('server_type_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='server_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='argos.ServerType'),
            preserve_default=False,
        ),
    ]
