# Generated by Django 2.0.2 on 2018-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('argos', '0006_device_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='group',
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
