# Generated by Django 2.0.2 on 2018-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0007_auto_20180511_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pltemperature',
            name='pl',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='pl_pck',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='pl_timestamp',
        ),
        migrations.AddField(
            model_name='payload',
            name='pl_data',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payload',
            name='pl_datetime',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='PlTemperature',
        ),
    ]
