# Generated by Django 2.0.2 on 2018-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0009_auto_20180910_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dev_desc',
            field=models.CharField(default='dev_desc', max_length=50),
            preserve_default=False,
        ),
    ]
