# Generated by Django 2.0.2 on 2018-10-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0010_device_dev_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='dev_type',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='payload',
            old_name='dev_eui',
            new_name='device',
        ),
    ]
