# Generated by Django 2.0.2 on 2019-01-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('argos', '0011_auto_20181005_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw_desc', models.CharField(max_length=50)),
                ('gw_serial', models.CharField(max_length=50)),
                ('gw_brand', models.CharField(max_length=50)),
                ('gw_model', models.CharField(max_length=50)),
                ('gw_latlong', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('server_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.ServerType')),
            ],
        ),
    ]
