# Generated by Django 2.1.7 on 2019-02-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0012_gateway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='gw_serial',
            new_name='gw_id',
        ),
    ]
