# Generated by Django 2.1.7 on 2019-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0013_auto_20190218_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='dev_type_shortdesc',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
