# Generated by Django 2.1.7 on 2019-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0014_devicetype_dev_type_shortdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='dev_type_interval',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4),
            preserve_default=False,
        ),
    ]
