# Generated by Django 2.2.3 on 2020-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0018_card_inst_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='inst_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
