# Generated by Django 2.2.3 on 2020-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0019_auto_20200116_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(default=1),
        ),
    ]
