# Generated by Django 2.2.3 on 2020-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0020_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_value',
            field=models.IntegerField(default=0),
        ),
    ]
