# Generated by Django 2.2.3 on 2020-01-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0022_auto_20200122_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_card_cod',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_status',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
