# Generated by Django 2.2.3 on 2020-01-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0023_auto_20200122_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='inst',
            name='inst_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inst',
            name='inst_dev_eui',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_account',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_card_cod',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_dev_eui',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_pulseC',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tr_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
