# Generated by Django 2.2.9 on 2020-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0024_auto_20200124_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_pulseC',
            field=models.IntegerField(default=0),
        ),
    ]
