# Generated by Django 3.1.6 on 2021-03-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from argos.models import InstallationType


def populate_installationtype(apps, schema_editor):
    installation_type = InstallationType(
        type_id = 1,
        desc = 'Instalação Consumidora'
    )
    installation_type.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('argos', '0025_auto_20200203_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
                ('mqtt_data_format', models.CharField(max_length=20)),
                ('rest_data_format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HTTPDeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
                ('shortdesc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HTTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('users', models.ManyToManyField(to='auth.User', blank=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.HTTPDeviceType')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.HTTPServer')),
            ],
        ),
        migrations.CreateModel(
            name='HTTPPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_rx', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('data_payload', models.CharField(max_length=256)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.HTTPDevice')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(populate_installationtype),
        migrations.CreateModel(
            name='InstallationPeriodHTTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ini', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.HTTPDevice')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPeriodLoraDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ini', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='card_cod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='card_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='card_is_used',
            new_name='is_used',
        ),
        migrations.RenameModel(
            old_name='DeviceType',
            new_name='LoraDeviceType',
        ),
        migrations.RenameField(
            model_name='LoraDeviceType',
            old_name='dev_type_id',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='LoraDeviceType',
            old_name='dev_type_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='LoraDeviceType',
            old_name='dev_type_shortdesc',
            new_name='shortdesc',
        ),
        migrations.RenameField(
            model_name='LoraDeviceType',
            old_name='dev_type_interval',
            new_name='interval',
        ),
        migrations.RenameModel(
            old_name='ServerType',
            new_name='LoraServer',
        ),
        migrations.RenameField(
            model_name='LoraServer',
            old_name='server_type_id',
            new_name='server_id',
        ),
        migrations.RenameField(
            model_name='LoraServer',
            old_name='server_type_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='LoraServer',
            old_name='server_type_data_format',
            new_name='mqtt_data_format',
        ),
        migrations.AddField(
            model_name='LoraServer',
            name='rest_data_format',
            field=models.CharField(max_length=20, default='hexa'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='gw_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='gw_id',
            new_name='gateway_id',
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='gw_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='gw_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='gw_latlong',
            new_name='latlong',
        ),
        migrations.RenameField(
            model_name='Gateway',
            old_name='server_type',
            new_name='server',
        ),
        migrations.AlterField(
            model_name='Gateway',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.LoraServer'),
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='LoraDevice',
        ),
        migrations.RenameField(
            model_name='LoraDevice',
            old_name='dev_eui',
            new_name='eui',
        ),
        migrations.RenameField(
            model_name='LoraDevice',
            old_name='dev_pwd',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='LoraDevice',
            old_name='dev_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='LoraDevice',
            old_name='server_type',
            new_name='server',
        ),
        migrations.AlterField(
            model_name='LoraDevice',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.LoraServer'),
        ),
        migrations.AlterField(
            model_name='LoraDevice',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.LoraDeviceType'),
        ),
        migrations.AddField(
            model_name='LoraDevice',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, blank=True),
        ),
        migrations.RenameModel(
            old_name='Payload',
            new_name='LoraPayload',
        ),
        migrations.RenameField(
            model_name='LoraPayload',
            old_name='pl_data',
            new_name='data_payload',
        ),
        migrations.RenameField(
            model_name='LoraPayload',
            old_name='pl_datetime',
            new_name='datetime_rx',
        ),
        migrations.RenameField(
            model_name='LoraPayload',
            old_name='pl_snr',
            new_name='snr',
        ),
        migrations.RenameField(
            model_name='LoraPayload',
            old_name='pl_rssi',
            new_name='rssi',
        ),
        migrations.AlterField(
            model_name='LoraPayload',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.LoraDevice'),
        ),
        migrations.AddField(
            model_name='LoraPayload',
            name='payload',
            field=models.JSONField(blank = True, null = True),
        ),
        migrations.RenameModel(
            old_name='Inst',
            new_name='Installation',
        ),
        migrations.RenameField(
            model_name='Installation',
            old_name='inst_cod',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='Installation',
            old_name='inst_ativo',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='Installation',
            name='device',
        ),
        migrations.RemoveField(
            model_name='Installation',
            name='inst_dev_eui',
        ),
        migrations.RemoveField(
            model_name='Installation',
            name='inst_email',
        ),
        migrations.RemoveField(
            model_name='Installation',
            name='inst_constant',
        ),
        migrations.AddField(
            model_name='Installation',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='Installation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, blank=True),
        ),
        migrations.AddField(
            model_name='Installation',
            name='installation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='argos.InstallationType'),
            preserve_default = False,
        ),
        migrations.AddField(
            model_name='Installation',
            name='http_devices',
            field=models.ManyToManyField(through='argos.InstallationPeriodHTTPDevice', to='argos.HTTPDevice'),
        ),
        migrations.AddField(
            model_name='Installation',
            name='lora_devices',
            field=models.ManyToManyField(through='argos.InstallationPeriodLoraDevice', to='argos.LoraDevice'),
        ),
        migrations.AddField(
            model_name='InstallationPeriodHTTPDevice',
            name='installation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='argos.Installation'),
            preserve_default = False,
        ),
        migrations.AddField(
            model_name='InstallationPeriodLoraDevice',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.Installation'),
        ),
        migrations.AddField(
            model_name='InstallationPeriodLoraDevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.LoraDevice'),
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_date',
            new_name='datetime_rx',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_inst_cod',
            new_name='installation_code',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_dev_eui',
            new_name='device_eui',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_card_cod',
            new_name='card_code',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_pulseC',
            new_name='pulseC',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_value',
            new_name='energy_value',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_account',
            new_name='energy_account',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_action',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='tr_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='Transaction',
            old_name='inst',
            new_name='installation',
        ),
        migrations.AlterField(
            model_name='Transaction',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='argos.Installation'),
        ),
        migrations.AlterField(
            model_name='Transaction',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='argos.LoraDevice'),
        ),
    ]
