# Generated by Django 3.1.6 on 2021-05-31 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('argos', '0026_auto_20210309_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.installation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='httpdevicetype',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='httpserver',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='httpserver',
            name='mqtt_data_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='httpserver',
            name='rest_data_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='installationtype',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loradevicetype',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loraserver',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loraserver',
            name='mqtt_data_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loraserver',
            name='rest_data_format',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='RechargeStationElectricVehicleOwnerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Manual', max_length=20)),
                ('max_battery_level_on_recharge', models.IntegerField(default=100)),
                ('min_battery_level_on_discharge', models.IntegerField(default=30)),
                ('recharge_start_time', models.TimeField(default=datetime.time(23, 0))),
                ('recharge_finish_time', models.TimeField(default=datetime.time(3, 0))),
                ('discharge_start_time', models.TimeField(default=datetime.time(17, 0))),
                ('discharge_finish_time', models.TimeField(default=datetime.time(20, 0))),
                ('min_battery_level_required', models.IntegerField(default=20)),
                ('electric_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.electricvehicle')),
                ('recharge_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.rechargestation')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeStationConsumerUnitOwnerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_sale_price', models.DecimalField(decimal_places=2, default=900, max_digits=8)),
                ('off_peak_sale_price', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('peak_purchase_price', models.DecimalField(decimal_places=2, default=700, max_digits=8)),
                ('off_peak_purchase_price', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('recharge_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.rechargestation')),
            ],
        ),
        migrations.CreateModel(
            name='RechargePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('status', models.CharField(default='Off', max_length=20)),
                ('recharge_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argos.rechargestation')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricVehicleElectricVehicleOwnerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Manual', max_length=20)),
                ('max_battery_level_on_recharge', models.IntegerField(default=80)),
                ('min_battery_level_on_discharge', models.IntegerField(default=50)),
                ('max_price_to_recharge', models.DecimalField(decimal_places=2, default=600.0, max_digits=8)),
                ('min_price_to_discharge', models.DecimalField(decimal_places=2, default=700.0, max_digits=8)),
                ('min_battery_level_required', models.IntegerField(default=20)),
                ('electric_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.electricvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricVehicleConsumerUnitOwnerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='Manual', max_length=20)),
                ('max_battery_level_on_recharge', models.IntegerField(default=100)),
                ('min_battery_level_on_discharge', models.IntegerField(default=30)),
                ('recharge_start_time', models.TimeField(default=datetime.time(23, 0))),
                ('recharge_finish_time', models.TimeField(default=datetime.time(3, 0))),
                ('discharge_start_time', models.TimeField(default=datetime.time(17, 0))),
                ('discharge_finish_time', models.TimeField(default=datetime.time(20, 0))),
                ('min_battery_level_required', models.IntegerField(default=20)),
                ('electric_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.electricvehicle')),
                ('recharge_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='argos.rechargestation')),
            ],
        ),
    ]
