# Generated by Django 3.2.6 on 2021-09-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argos', '0027_auto_20210531_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('subgroup', models.CharField(max_length=3)),
                ('classif_id', models.IntegerField(default=0)),
                ('classif_desc', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Valor da tarifa',
                'verbose_name_plural': 'Valores da tarifa',
            },
        ),
        migrations.CreateModel(
            name='TariffFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_id', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=5, default=0.0, max_digits=8)),
                ('datetime_ini', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Valor de bandeira tarifária',
                'verbose_name_plural': 'Valores de bandeira tarifária',
            },
        ),
        migrations.CreateModel(
            name='TaxIcms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ini', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField()),
                ('valueRes1', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('valueRes2', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('valueRur1', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('valueRur2', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('valueOther', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Valor de ICMS',
                'verbose_name_plural': 'Valores de ICMS',
            },
        ),
        migrations.CreateModel(
            name='TaxPisCofins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_ini', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField()),
                ('value_pis', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('value_cofins', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Valor de PIS/COFINS',
                'verbose_name_plural': 'Valores de PIS/COFINS',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='electricvehicle',
            options={'verbose_name': 'Veículo Elétrico', 'verbose_name_plural': 'Veículos Elétricos'},
        ),
        migrations.AlterModelOptions(
            name='electricvehicleconsumerunitownersettings',
            options={'verbose_name': 'Preferências de um PUC para recarga/descarga de seu VE em uma estação qualquer', 'verbose_name_plural': 'Preferências de um PUC para recarga/descarga de seu VE em uma estação qualquer'},
        ),
        migrations.AlterModelOptions(
            name='electricvehicleelectricvehicleownersettings',
            options={'verbose_name': 'Preferências de um PVE para recarga/descarga de seu VE em uma estação qualquer', 'verbose_name_plural': 'Preferências de um PVE para recarga/descarga de seu VE em uma estação qualquer'},
        ),
        migrations.AlterModelOptions(
            name='httpdevice',
            options={'verbose_name': 'Dispositivo HTTP', 'verbose_name_plural': 'Dispositivos HTTP'},
        ),
        migrations.AlterModelOptions(
            name='httpdevicetype',
            options={'verbose_name': 'Tipo de Dispositivo HTTP', 'verbose_name_plural': 'Tipos de Dispositivo HTTP'},
        ),
        migrations.AlterModelOptions(
            name='httppayload',
            options={'verbose_name': 'Payload HTTP', 'verbose_name_plural': 'Payloads HTTP'},
        ),
        migrations.AlterModelOptions(
            name='httpserver',
            options={'verbose_name': 'Servidor HTTP', 'verbose_name_plural': 'Servidores HTTP'},
        ),
        migrations.AlterModelOptions(
            name='installation',
            options={'verbose_name': 'Instalação', 'verbose_name_plural': 'Instalações'},
        ),
        migrations.AlterModelOptions(
            name='installationperiodhttpdevice',
            options={'verbose_name': 'Período de Instalação do Dispositivo HTTP', 'verbose_name_plural': 'Períodos de Instalação dos Dispositivos HTTP'},
        ),
        migrations.AlterModelOptions(
            name='installationperiodloradevice',
            options={'verbose_name': 'Período de Instalação do Dispositivo LoRa', 'verbose_name_plural': 'Períodos de Instalação dos Dispositivos LoRa'},
        ),
        migrations.AlterModelOptions(
            name='installationtype',
            options={'verbose_name': 'Tipo de Instalação', 'verbose_name_plural': 'Tipos de Instalação'},
        ),
        migrations.AlterModelOptions(
            name='loradevice',
            options={'verbose_name': 'Dispositivo LoRa', 'verbose_name_plural': 'Dispositivos LoRa'},
        ),
        migrations.AlterModelOptions(
            name='loradevicetype',
            options={'verbose_name': 'Tipo de Dispositivo LoRa', 'verbose_name_plural': 'Tipos de Dispositivo LoRa'},
        ),
        migrations.AlterModelOptions(
            name='lorapayload',
            options={'verbose_name': 'Payload LoRa', 'verbose_name_plural': 'Payloads LoRa'},
        ),
        migrations.AlterModelOptions(
            name='loraserver',
            options={'verbose_name': 'Servidor LoRa', 'verbose_name_plural': 'Servidores LoRa'},
        ),
        migrations.AlterModelOptions(
            name='rechargepoint',
            options={'verbose_name': 'Ponto de Recarga', 'verbose_name_plural': 'Pontos de Recarga'},
        ),
        migrations.AlterModelOptions(
            name='rechargestation',
            options={'verbose_name': 'Estação de Recarga', 'verbose_name_plural': 'Estações de Recarga'},
        ),
        migrations.AlterModelOptions(
            name='rechargestationconsumerunitownersettings',
            options={'verbose_name': 'Preferências de um PUC para recarga/descarga de um VE qualquer em sua estação', 'verbose_name_plural': 'Preferências de um PUC para recarga/descarga de um VE qualquer em sua estação'},
        ),
        migrations.AlterModelOptions(
            name='rechargestationelectricvehicleownersettings',
            options={'verbose_name': 'Preferências de um PVE para recarga/descarga de seu VE em sua estação', 'verbose_name_plural': 'Preferências de um PVE para recarga/descarga de seu VE em sua estação'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
